---
- name: Install Oh My Zsh # noqa: latest
  ansible.builtin.git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: ~/.oh-my-zsh
    depth: 1

- name: Set ZSH_CUSTOM env var
  ansible.builtin.set_fact: zsh_custom="{{ lookup('ansible.builtin.env', 'ZSH_CUSTOM', default='~/.oh-my-zsh/custom') }}"
 
- name: Install zsh-autosuggestions plugin # noqa: latest
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: "{{zsh_custom}}/plugins/zsh-autosuggestions"
    depth: 1

- name: Install zsh-history-substring-search plugin # noqa: latest
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-history-substring-search
    dest: "{{zsh_custom}}/plugins/zsh-history-substring-search"
    depth: 1
 
- name: Install zsh-syntax-highlighting plugin # noqa: latest
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: "{{zsh_custom}}/plugins/zsh-syntax-highlighting"
    depth: 1

- name: Install spaceship theme
  ansible.builtin.git:
    repo: https://github.com/spaceship-prompt/spaceship-prompt.git
    dest: "{{zsh_custom}}/themes/spaceship-prompt"
    depth: 1

- name: Symlink spaceship.zsh-theme to oh-my-zsh custom themes directory
  file:
    src: "{{zsh_custom}}/themes/spaceship-prompt/spaceship.zsh-theme"
    dest: "{{zsh_custom}}/themes/spaceship.zsh-theme"
    state: link

- name: Install Vundle
  ansible.builtin.git:
    repo: https://github.com/VundleVim/Vundle.vim.git
    dest: "~/.vim/bundle/Vundle.vim"
    depth: 1

- name: Install Vim plugins
  command: vim -E -s -c "source $HOME/.vimrc" -c PluginInstall -c qa

- name: Install YCMD
  command: cd ~/.vim/bundle/YouCompleteMe && python3 install.py
